# Generated by Django 3.1.4 on 2023-03-04 11:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_discount',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='room',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_discount_percent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rate',
        ),
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='room.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.TextField(choices=[('King', 'King'), ('Luxury', 'Luxury'), ('Normal', 'Normal'), ('Economic', 'Economic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_include',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Breakfast', 'Breakfast'), ('Bar', 'Bar'), ('Free WiFi', 'Free WiFi'), ('Room service', 'Room service'), ('Private Bathroom', 'Private Bathroom')], max_length=30),
        ),
    ]
