# Generated by Django 3.1.4 on 2023-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20230304_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
