# Generated by Django 3.1.4 on 2023-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20230414_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ImageField(blank=True, upload_to='review_images/'),
        ),
    ]
