# Generated by Django 3.1.4 on 2023-04-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20230414_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
