# Generated by Django 3.1.4 on 2023-04-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_auto_20230423_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_area',
            field=models.CharField(default='', max_length=15),
        ),
    ]
