# Generated by Django 3.1.4 on 2023-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_room_room_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel_name',
            field=models.CharField(max_length=50),
        ),
    ]
