# Generated by Django 3.1.4 on 2023-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_auto_20230423_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
