# Generated by Django 3.1.4 on 2023-05-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0022_auto_20230424_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='tourist_place_images/')),
                ('description', models.TextField()),
                ('distance_from_room', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.TextField(choices=[('Hotel', 'Hotel'), ('HomeStay', 'HomeStay'), ('Normal', 'Normal'), ('Vip', 'Vip'), ('King', 'King')], max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='tourist_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.touristplace'),
        ),
    ]
