# Generated by Django 3.1.4 on 2023-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0023_auto_20230501_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tourist_place',
        ),
        migrations.AddField(
            model_name='room',
            name='tourist_place',
            field=models.ManyToManyField(to='room.TouristPlace'),
        ),
    ]
